Create a page to view the list of users
IT-Academy-Social-Projects-KRV/Logistman-Client pull request #26
Opened 2022-06-04 14:46 UTC by AndriiChepeliuk

--- Add ---

- added page with list of users;
- added result page "403" if user are not allowed to some page
- added menuItems for IdentityRole "Logist"

--- Change ---

services/authentication.js - go to page after authentication depending on the IdentityRole

2022-06-04 23:01 UTC, Grasmus commented on src/services/users.js
> +
Remove empty line

2022-06-04 23:01 UTC, Grasmus commented on src/services/users.js
> +        )
What will happen if error occurs?

2022-06-04 23:01 UTC, Grasmus commented on src/privateRoute.js
> +        //return <Route component={() => <Redirect to="/login" />} />;
What is it?

2022-06-05 11:55 UTC, Grasmus commented on src/components/navigation/menu.jsx
> +    switch (decodedAccessToken.role) {
I think it is better here to use dictionary with key Role and value MenuItems

2022-06-05 19:30 UTC, marynakernychna requested changes
Also, the Logist button should not display the "Add car" button, so that when you click on it, an error window will be displayed

2022-06-05 19:30 UTC, marynakernychna commented on src/api/users.js
> +  static getAllIdentityUsers() {
Why don't you call it "getAllUsers"?

2022-06-05 19:30 UTC, marynakernychna commented on src/components/navigation/menu.jsx
> +    let accessToken = tokenService.getLocalAccessToken();
We should not work with tokens in components

2022-06-05 19:30 UTC, marynakernychna commented on src/components/navigation/menu.jsx
> +    switch (decodedAccessToken.role) {
You can get the role of a user from Redux, it is already recorded there

2022-06-05 19:30 UTC, marynakernychna commented on src/components/navigation/menuItems.js
> +import users_icon from "../../assets/images/users_icon.png"
Please change from .png to .svg (files not created by you will be modified later)

2022-06-05 19:30 UTC, marynakernychna commented on src/components/navigation/menuItems.js
> +export const menuUserItems = [
Why don't you call it "userMenuItems"?

2022-06-05 19:30 UTC, marynakernychna commented on src/components/navigation/menuItems.js
> +export const menuLogistItems = [
Why don't you call it "logistMenuItems"?

2022-06-05 19:30 UTC, marynakernychna commented on src/components/users/index.jsx
> +        <div className="allIdentityUsersBody">
Why don't you call it "usersPageBody"?

2022-06-05 19:30 UTC, marynakernychna commented on src/components/users/index.jsx
> +
Remove the extra empty ine

2022-06-05 19:30 UTC, marynakernychna commented on src/components/users/index.jsx
> +function IdentityUserListPage() {
Why don't you call it "ManageUsersPage"?

2022-06-05 19:30 UTC, marynakernychna commented on src/components/users/user/index.jsx
> +
Remove the extra empty line

2022-06-05 19:30 UTC, marynakernychna commented on src/constants/api/urls.js
> +    GET_ALL_IDENTITY_USERS: USER_URL
Why don't you call it "GET_ALL_USERS"?

2022-06-05 19:30 UTC, marynakernychna commented on src/reducers/authReducer.js
> +            if (decodedAccessToken.role === userRoles.LOGIST) {
It is necessary to make from 2 if — one in which condition will be checked whether the role is in an array of userRoles. And in the body — tokens are set and change the role & the isAuthUser from the state

2022-06-05 19:30 UTC, marynakernychna commented on src/services/authentication.js
> +                switch (decodedAccessToken.role) {
You can get the role of a user from Redux, it is already recorded there

2022-06-05 19:30 UTC, marynakernychna commented on src/services/authentication.js
> +                        history.push("/login");
I think you should display an error message

2022-06-05 19:30 UTC, marynakernychna commented on src/services/users.js
> +export async function getAllIdentityUsers() {
Why don't you call it "getAllUsers"?

2022-06-06 09:32 UTC, marynakernychna approved these changes

2022-06-06 09:39 UTC, Grasmus approved these changes

2022-06-06 09:39 UTC, merged