Feat/dv 135/create page to confirm goods delivery for driver
IT-Academy-Social-Projects-KRV/Logistman-Client pull request #46
Opened 2022-07-18 23:20 UTC by Eugene-pas

2022-07-18 23:40 UTC, Grasmus commented on src/assets/scss/assets/pages/_confirmTripOfferPage.scss
> +}
Add empty line in the eof

2022-07-18 23:40 UTC, Grasmus commented on src/components/confirmGoodsDeliveryForDriver/index.jsx
> +                                    console.log(iter, item);
Remove console log

2022-07-18 23:40 UTC, Grasmus commented on src/components/confirmGoodsDeliveryForDriver/infoTrip/index.jsx
> +                                                <p>{moment(props.tripInfo.departureDate).format('LL HH:mm') + " "}</p>
Please, use UTC date

2022-07-18 23:40 UTC, Grasmus commented on src/components/confirmGoodsDeliveryForDriver/offers/index.jsx
> +                    console.log("Confirm", {offerId: props.offerData.id, Role: offerRoles.DRIVER, isConfirmed: true});
Remove console log

2022-07-18 23:40 UTC, Grasmus commented on src/components/confirmGoodsDeliveryForDriver/offers/index.jsx
> +                    console.log("Decline", {offerId: props.offerData.id, Role: offerRoles.DRIVER, isConfirmed: false});
Remove console log

2022-07-18 23:40 UTC, Grasmus commented on src/components/confirmGoodsDeliveryForDriver/index.jsx
> +    console.log(offers);
Remove console log

2022-07-18 23:41 UTC, marynakernychna reviewed
Remove all console logs

2022-07-18 23:41 UTC, marynakernychna commented on src/assets/scss/assets/pages/_confirmInfoTrip.scss
> +  }
Align code

2022-07-18 23:41 UTC, marynakernychna commented on src/assets/scss/assets/pages/_confirmOffers.scss
> +
Remove the blank line

2022-07-18 23:41 UTC, marynakernychna commented on src/assets/scss/assets/pages/_confirmTripOfferPage.scss
> +  .titel{
titel?

2022-07-18 23:41 UTC, marynakernychna commented on src/assets/scss/assets/pages/_confirmTripOfferPage.scss
> +}
Add the blank line

2022-07-18 23:41 UTC, marynakernychna commented on src/assets/scss/main.scss
> +@import "./assets/pages/confirmOffers";
Import component styles to page files

2022-07-18 23:41 UTC, marynakernychna commented on src/components/confirmGoodsDeliveryForDriver/index.jsx
> +                <h1 className="titel">Active Trip</h1>
titel?

2022-07-18 23:43 UTC, marynakernychna commented on src/constants/api/urls.js
> +    GET_BY_NEAR_ROUT: OFFERS_URL + "/near-route",
GET_BY_NEAR_ROUTE

2022-07-18 23:46 UTC, marynakernychna requested changes
Starts with an error

2022-07-19 05:59 UTC, Grasmus approved these changes

2022-07-19 06:00 UTC, marynakernychna approved these changes

2022-07-19 06:01 UTC, merged